#!/bin/sh
# This script was created by make-mzscheme-launcher

# {{{ bindir
bindir="/usr/bin"
# }}} bindir

exec "${bindir}/racket" -N "$0" '-I' 'scheme/init' '-qt-' '/home/ch/Documents/racketess/main.rkt'  ${1+"$@"}
